/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_beyongha_softwareexperimentteam15_NativeCall */

#ifndef _Included_com_example_beyongha_softwareexperimentteam15_NativeCall
#define _Included_com_example_beyongha_softwareexperimentteam15_NativeCall
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_beyongha_softwareexperimentteam15_NativeCall
 * Method:    string
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_beyongha_softwareexperimentteam15_NativeCall_string
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
